# Generated by Django 3.2.5 on 2021-07-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_block_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='color',
            field=models.CharField(choices=[('NT', 'nnnttss'), ('BL', 'gallery__item--purple'), ('BS', 'gallery__item--blue'), ('OR', 'gallery__item--orange')], default='NT', max_length=2),
        ),
    ]
