# Generated by Django 3.2.5 on 2021-07-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_teacher_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='url_to',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='block',
            name='color',
            field=models.CharField(choices=[('nnnttss', 'nnnttss'), ('gallery__item--purple', 'gallery__item--purple'), ('gallery__item--blue', 'gallery__item--blue'), ('gallery__item--orange', 'gallery__item--orange')], default='nnnttss', max_length=40),
        ),
    ]
