# Generated by Django 3.2.5 on 2021-08-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210722_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberPhone', models.CharField(max_length=255)),
                ('fullName', models.CharField(max_length=255)),
            ],
        ),
    ]
