# Generated by Django 3.2.5 on 2021-08-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_leeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='leeds',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='leeds',
            name='fullName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
