# Generated by Django 3.2.5 on 2021-09-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_leeds_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClicksSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('instagram', 'instagram'), ('youtube', 'youtube'), ('telegram', 'telegram'), ('whatsapp', 'whatsapp'), ('facebook', 'facebook')], max_length=255)),
            ],
        ),
    ]
